### PR TITLE
fix: query response and some refmt

### LINKED ISSUE #6: Error in the returned response
Hey ! 👋

This is awesome! Thank you for making this. 🙏

Well, I'm having issues using `useQuery` with this library. 

It seems there is a small bug in the transformation of the graphql response. I always receive `Data(response)` and never `Loading` or `Error`.

By changing that :

```reason
(
    switch (result) {
    | {data: Some(data)} => Data(data)
    | {error: Some(error)} => Error(error)
    | {loading: true} => Loading
    | _ => NoData
    },
    result,
);
```

to :

```reason
(
    switch (result) {
    | {loading: true} => Loading
    | {error: Some(error)} => Error(error)
    | {data: Some(data)} => Data(data)
    | _ => NoData
    },
    result,
  );
```

it works again! (and it seems closer to [the official source](https://github.com/apollographql/reason-apollo/blob/master/src/graphql-types/ReasonApolloQuery.re#L79))

I can create a PR if that's okay with you! 😊

### PR DESCRIPTION
**Pull request by baransu**
Fixes #6 and add a little bit of `refmt`. If you don't want the `refmt` I'll resubmit PR without it.

### CODE REVIEW

**Comment by fakenickels** [comment]
Thanks!

**Comment by fakenickels** [comment]
Released under v1.0.3

**Comment by LeoLeBras** [comment]
Awesome 🔥

**Comment by fakenickels** [comment]
@all-contributors add @baransu for bug and code

**Pull request merged**
