### PR TITLE
Feat/full result from mutation promise

### PR DESCRIPTION
**Pull request by mbirkegaard**
This makes the promise returned by `mutate` resolve to a tuple of a (simple, full) result similar to what the mutation hook does, as discussed in #99.

Since it's breaking anyway I also changed the `Error` to `Errors` in the variant (it's also plural in the record from js). Also removed a dependency on `ReasonApolloTypes.executionResult`.

This PR assumes #97 will be merged.

### CODE REVIEW

**Comment by fakenickels** [comment]
oh this makes a lot of sense! I really liked the idea but it is a quite a breaking change.
I'm going to await a bit more so we can merge this after

**Comment by mbirkegaard** [comment]
> oh this makes a lot of sense! I really liked the idea but it is a quite a breaking change.
> I'm going to await a bit more so we can merge this after

Okay. Figured I might as well get the PR for this up since #97 is breaking anyway.

**Comment by mbirkegaard** [comment]
Had forgotten to mark this ready for review after #97 got merged.

**Comment by mbirkegaard** [comment]
@fakenickels Are we fine with merging this? Or is there some non-breaking stuff we should get in first?

**Comment by fakenickels** [comment]
I think we are!

**Pull request merged**
